version: '3.4'
services:
    AuthConverter:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx.js:/etc/nginx/nginx.js
        network_mode: host
